### ISSUE TITLE
TypeError: Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by alexlrobertson** [xBytez/slackbotapi#34]
Using the example code, I get this error:

```
url.js:110
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:110:11)
    at Object.urlParse [as parse] (url.js:104:5)
    at WebSocket.initAsClient (./node_modules/ws/lib/WebSocket.js:550:23)
    at new WebSocket (./node_modules/ws/lib/WebSocket.js:74:18)
    at slackAPI.connectSlack (./node_modules/slackbotapi/index.js:172:15)
    at ./node_modules/slackbotapi/index.js:121:14
    at Request._callback (./node_modules/slackbotapi/index.js:142:24)
    at Request.self.callback (./node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (./node_modules/request/request.js:1063:14)
```

**Comment by franciskim** [comment]
strange one, have you made any modifications at all?

**Comment by alexlrobertson** [comment]
No modifications have been made. I've tried on node `0.12` and `4.0` and `npm@2` and `npm@3`. Same issue.

**Comment by alexlrobertson** [comment]
Looks like the auth is invalid.

```
{ ok: false, error: 'invalid_auth' }
```

What type of token is required? I have a `Bot` token.

**Comment by franciskim** [comment]
The RTM API token (which is the bot token)

**Comment by alexlrobertson** [comment]
Looks like it was an issue with their auth servers. Its up and running now. It would be nice to add a case to catch an error like that.

**Comment by crishelyumul** [comment]
I resolved mine by exporting the url of my repo.
